services:
  bot:
    container_name: gprdb_bot
    image: morenicano/gprdb_bot:latest
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - gprdb
    depends_on:
      - postgres
      - webapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    container_name: gprdb_postgres
    image: postgres:latest
    environment:
      PGID: 65544
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      UID: 1026
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${DATA_FOLDER_PATH}/postgres_data:/var/lib/postgresql/data
    networks:
      - gprdb

  webapp:
    container_name: gprdb_webapp
    image: morenicano/gprdb_webapp:latest
    ports:
      - "${WEBAPP_PORT}:5000"
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      DISCORD_ADMIN_ROLE_ID: ${DISCORD_ADMIN_ROLE_ID}
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}
      PGID: ${PGID}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      UID: ${UID}
    volumes:
       - ${DATA_FOLDER_PATH}/templates:/app/templates
    networks:
      - gprdb
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    container_name: gprdb_redis
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - gprdb

volumes:
  postgres_data:

networks:
  gprdb:
    driver: bridge
    external: false